#![allow(dead_code, unused_mut)]

use std::ffi::{CStr, CString};
use std::os::raw::c_char;

/// Current ABI version that plugins must target
pub const CORE_ABI_VERSION: u32 = 1;

/// Hook bit flags for the plugin hook mask
pub const HOOK_PRE_BUILD: u32 = 1;
pub const HOOK_POST_CONVERT: u32 = 2;
pub const HOOK_POST_RENDER: u32 = 4;
pub const HOOK_POST_BUILD: u32 = 8;

/// C ABI PluginInfo struct returned by `norgolith_plugin_init`
#[repr(C)]
pub struct PluginInfo {
    /// Which version of plugin.h this .so was compiled against
    pub abi_version: u32,
    /// Human-readable plugin name for error messages
    pub name: *const c_char,
    /// Semantic version for debugging (not validation)
    pub version: *const c_char,
}

/// Function pointer type for plugin hooks
pub type PluginFn = extern "C" fn(*const c_char) -> *mut c_char;

/// Function pointer type for freeing plugin-allocated strings
pub type FreeStringFn = extern "C" fn(*mut c_char);

/// Context for the pre_build hook
#[derive(serde::Deserialize)]
pub struct PreBuildContext {
    pub site_config: serde_json::Value,
    pub pages_dir: String,
    pub output_dir: String,
}

/// Context for post_convert and post_render hooks
#[derive(serde::Deserialize)]
pub struct TransformContext {
    pub html: String,
    pub metadata: serde_json::Value,
    pub rel_path: String,
}

/// Context for the post_build hook
#[derive(serde::Deserialize)]
pub struct PostBuildContext {
    pub site_config: serde_json::Value,
    pub pages_dir: String,
    pub output_dir: String,
}

/// Builder for registering plugin hooks
pub struct PluginBuilder {
    name: &'static str,
    version: &'static str,
    pre_build: Option<PluginFn>,
    post_convert: Option<PluginFn>,
    post_render: Option<PluginFn>,
    post_build: Option<PluginFn>,
}

impl PluginBuilder {
    /// Create a new plugin builder
    pub fn new(name: &'static str, version: &'static str) -> Self {
        Self {
            name,
            version,
            pre_build: None,
            post_convert: None,
            post_render: None,
            post_build: None,
        }
    }

    /// Register a pre_build hook
    pub fn on_pre_build<F>(mut self, _handler: F) -> Self
    where
        F: Fn(PreBuildContext) -> Result<Option<String>, String> + 'static,
    {
        // Bridge function will be generated by the macro
        self
    }

    /// Register a post_convert hook
    pub fn on_post_convert<F>(mut self, _handler: F) -> Self
    where
        F: Fn(TransformContext) -> Result<Option<String>, String> + 'static,
    {
        // Bridge function will be generated by the macro
        self
    }

    /// Register a post_render hook
    pub fn on_post_render<F>(mut self, _handler: F) -> Self
    where
        F: Fn(TransformContext) -> Result<Option<String>, String> + 'static,
    {
        // Bridge function will be generated by the macro
        self
    }

    /// Register a post_build hook
    pub fn on_post_build<F>(mut self, _handler: F) -> Self
    where
        F: Fn(PostBuildContext) -> Result<Option<String>, String> + 'static,
    {
        // Bridge function will be generated by the macro
        self
    }

    /// Finalize registration (placeholder - real implementation will be in macro)
    pub fn register(self) {
        // This is a placeholder - the real implementation will use the macro
    }
}

/// Helper to convert Rust string to C string for plugin return values
pub fn to_c_string(s: &str) -> *mut c_char {
    CString::new(s)
        .unwrap_or_default()
        .into_raw()
}

/// Helper to convert C string from plugin input to Rust string
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn from_c_string(ptr: *const c_char) -> Option<String> {
    if ptr.is_null() {
        return None;
    }
    unsafe { CStr::from_ptr(ptr) }
        .to_str()
        .ok()
        .map(|s| s.to_string())
}

/// Register a plugin with the given name and version
///
/// This macro generates the required `norgolith_plugin_init` function and
/// bridge functions for each registered hook.
///
/// # Example
///
/// ```rust
/// use norgolith_plugin_sdk::*;
///
/// register_plugin!("my-plugin", "0.1.0")
///     .on_post_render(|ctx| {
///         // Transform the HTML
///         Ok(Some(ctx.html))
///     })
///     .register();
/// ```
#[macro_export]
macro_rules! register_plugin {
    ($name:expr, $version:expr) => {
        $crate::PluginBuilder::new($name, $version)
    };
}
