name: build

on:
  push:
    branches: [master]
    paths:
      - "src/**/*.rs"
      - "Cargo.*"
      - "flake.*"
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/*.yml"
      - "src/**/*.rs"
      - "Cargo.*"
      - "flake.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - uses: dorny/paths-filter@v3
        id: flake_changes
        with:
          filters: |
            flake_files:
              - "flake.*"
      - name: Run nix flake check
        if: steps.flake_changes.outputs.flake_files == 'true'
        run: nix flake check
      - uses: cachix/cachix-action@v15
        with:
          name: ntbbloodbath
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: nix develop . -c cargo build --release

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@v9
      - uses: dorny/paths-filter@v3
        id: flake_changes
        with:
          filters: |
            flake_files:
              - "flake.*"
      - name: Run nix flake check
        if: steps.flake_changes.outputs.flake_files == 'true'
        run: nix flake check
      - uses: cachix/cachix-action@v15
        with:
          name: ntbbloodbath
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: nix develop . -c cargo build --release
