name: release

on:
  push:
    tags:
      - "norgolith-v*"
      - "norgolith-plugin-sdk-v*"
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    if: ${{ startsWith(github.ref_name, 'norgolith-v') && !startsWith(github.ref_name, 'norgolith-plugin-sdk-v') }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      # Do not cancel the build process if any of them fails
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os_name: Linux-aarch64
            os: ubuntu-24.04
            target: aarch64-unknown-linux-musl
          - os_name: Darwin-x86_64
            os: macos-latest-large
            target: x86_64-apple-darwin
          - os_name: Darwin-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v6
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: lith
          changes-file: ""
          extra-files: |
            README.md
            LICENSE
          target: ${{ matrix.platform.target }}

  publish-sdk:
    name: Publish SDK to crates.io
    if: ${{ startsWith(github.ref_name, 'norgolith-plugin-sdk-v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p norgolith-plugin-sdk
